// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserFromRefresh = `-- name: GetUserFromRefresh :one

SELECT user_id,expires_at,revoked_at FROM refresh_tokens WHERE token=$1
`

type GetUserFromRefreshRow struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) GetUserFromRefresh(ctx context.Context, token string) (GetUserFromRefreshRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefresh, token)
	var i GetUserFromRefreshRow
	err := row.Scan(&i.UserID, &i.ExpiresAt, &i.RevokedAt)
	return i, err
}

const login = `-- name: Login :one

SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users WHERE email=$1
`

func (q *Queries) Login(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, login, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const resetUsers = `-- name: ResetUsers :execresult

DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, resetUsers)
}

const revokeToken = `-- name: RevokeToken :execresult

UPDATE refresh_tokens
SET revoked_at=NOW(), updated_at=NOW()
WHERE token=$1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) (sql.Result, error) {
	return q.db.ExecContext(ctx, revokeToken, token)
}

const storeRefreshToken = `-- name: StoreRefreshToken :one

INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at, revoked_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    $3,
    NULL
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type StoreRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, storeRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateCreds = `-- name: UpdateCreds :one

UPDATE users
SET updated_at=NOW(), email=$1, hashed_password=$2
WHERE id=$3
RETURNING id, created_at, updated_at, email
`

type UpdateCredsParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

type UpdateCredsRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) UpdateCreds(ctx context.Context, arg UpdateCredsParams) (UpdateCredsRow, error) {
	row := q.db.QueryRowContext(ctx, updateCreds, arg.Email, arg.HashedPassword, arg.ID)
	var i UpdateCredsRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const upgradeToChirpyRed = `-- name: UpgradeToChirpyRed :execresult

UPDATE users
SET is_chirpy_red=TRUE
WHERE id=$1
`

func (q *Queries) UpgradeToChirpyRed(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.db.ExecContext(ctx, upgradeToChirpyRed, id)
}
